#%RAML 1.0 NamedExample


 - productId: 100
   productName: "Hp Pavilion Laptop"
   price: 70000.00
   mfgdate: "18-07-2022"
   brand: "HP"
   emailAddress: "abc@cog.com"


 - productId: 101
   productName: "Dell Laptop"
   price: 75000.00
   mfgdate: "17-07-2022"
   brand: "Dell"
   emailAddress: "abc@cog.com"